### ISSUE TITLE
redirection 제대로 동작하지 않음

### ISSUE THREAD

**Issue by Eingerjar** [Eingerjar/Minishell#31]
redirection이 정상적으로 동작하지 않음
```bash
>echo hello
output type:0 name:
```
name이 제대로 flist 없는 것으로 보임

**Comment by Paul2021-R** [comment]
<img width="445" alt="Screen Shot 2022-06-26 at 4 00 06 PM" src="https://user-images.githubusercontent.com/80471693/175803289-668a6cf2-a2b3-43ed-9f1e-341a0db8a7ae.png">
pipe가 안 닫히는지, 정상적으로 만들어는 지는데, 멈춰 있음

**Comment by Paul2021-R** [comment]
외부 함수의 경우 문제가 없음. 그러나 write 를 활용한 echo 빌트인의 경우 정상적으로 닫히지 않고 계속 대기하는 모습을 보임.

**Comment by Paul2021-R** [comment]
빌트인이 내부에서 프로세스로 작동했을 때 표준 입출력이 있는 경우, 출력을 하도록 설정할 시 정상적으로 마무리 되지 않는 것으로 보여짐.  따라서 이를 해결하려면 출력 하는 함수의 경우 빌트인이라고 해도 프로세스로 실행되야 할 것으로 보여짐.

**Comment by Paul2021-R** [comment]
출력 하는 빌트인을 제외한 경우만 프로세스 내에서 진행해야 할 것으로 보임 
* cd : 내부 프로세스 실행 필요
* echo : 무조건 자식에서 실행 필요
* env : 무조건 자식에서 실행 필요 
* export : 인자가 없을 경우 자식, 인자가 있을 경우(세팅시) 내부 프로세스에서 실행 필요 
* pwd : 자식에서 실행(큰 상관 없으니)
* unset : 내부에서 실행 
* exit : 내부에서 실행
