### ISSUE TITLE
g_global.last_exitcode

### ISSUE THREAD

**Issue by Eingerjar** [Eingerjar/Minishell#33]
https://github.com/Eingerjar/Minishell/blob/dd633eca1f8403beaec0256d4326d61361839386/src/here_heredoc_check.c#L30

지난 명령어가 실패로 끝났을 경우 0이 아닌 숫자로 설정이 되는 데 heredoc_check함수에서 heredoc이 실패한 것으로 판단되어 버립니다.

https://github.com/Eingerjar/Minishell/blob/dd633eca1f8403beaec0256d4326d61361839386/src/here_fork_heredoc.c#L27

fork_heredoc에서 바로 g_global.last_exitcode 설정되는 것을 수정하거나 처음 heredoc_check함수에서 g_global.last_exitcode를 잠시 tmp에 저장하고 성공하면 다시 g_global.alst_exitcode에 저장해주는 과정이 필요할 것 같습니다

**Comment by Paul2021-R** [comment]
```C
#include "../includes/minishell.h"

int	heredoc_check(char *line, char *installed)
{
	char	**chunks;
	int		chunk_height;
	t_flist	**heredoc;
	int		heredocnum;
	int		prev_last;

	prev_last = g_global.last_exitcode; // 임시 설정 
	g_global.last_exitcode = 0; // 0으로 할당 
	chunks = vertical_split(line);
	chunk_height = check_height(line);
	heredocnum = 0;
	heredoc = pre_heredoc(chunks, chunk_height, &heredocnum);
	if (heredocnum != 0)
		fork_heredoc(heredoc, chunk_height, installed);
	free_heredoc(heredoc, chunk_height);
	chunk_free(chunks, chunk_height);
	if (g_global.last_exitcode != 0)
		return (TRUE);
	else
	{
		g_global.last_exitcode = prev_last; // 이후 기존의 값으로 변경
		return (FALSE);
	}
}

```

**Comment by Paul2021-R** [comment]
해당 부분 DEV 머지되어 있습니다 :)
