### ISSUE TITLE
cmd error msg

### ISSUE THREAD

**Issue by Paul2021-R** [Eingerjar/Minishell#39]
<img width="353" alt="스크린샷 2022-06-26 오전 4 57 41" src="https://user-images.githubusercontent.com/80471693/175788810-741ce670-94d2-4e10-b91b-a874f0850696.png">

에러메시지 출력에서 파이프로 연결하여 진행 시 마지막 커맨드에 대한 미출력 발생

**Comment by Eingerjar** [comment]
첫번째 프로세스가 비정상적으로 종료될 때 다른 프로세스를 종료시는 키는 로직 때문에 에러가 발생하였습니다.
