### ISSUE TITLE
cd ..만 적용되는 문제

### ISSUE THREAD

**Issue by Eingerjar** [Eingerjar/Minishell#49]
https://github.com/Eingerjar/Minishell/blob/0deae2628f009faeb17eaf2be04bea3a919036e1/src/builtin_cd.c#L75

여기서
```
cd ../다른 경로
```
위와 같이 ..만 판단하고 다른 경로는 찾을 수 없는 문제가 있습니다!

**Comment by Paul2021-R** [comment]
fix 완료
